apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redis-server
  description: Redis Server App
  tags:
    - nosql
    - redis
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=redis-server'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: staff-health-app
  dependsOn: [Component:sh-db]
