apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hugo-staff-health-app
  labels:
    apps.tanzu.vmware.com/workload-type: myweb
    app.kubernetes.io/part-of: sh-web
    #apps.tanzu.vmware.com/has-tests: true
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/HugoXiao1984/staff-health
      ref:
        branch: main
