apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sh-appserver
  description: sh App Server
  tags:
    - python
  annotations:
    'backstage.io/kubernetes-label-selector': 'sh-appserver'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: staff-health-app
